from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseRedirect

from . import views


admin.autodiscover()

urlpatterns = [
    url(r'^provider/add', views.Provider().add, name="add_provider"),
    url(r'^provider/export', views.Provider().export, name="export_provider"),
    url(r'^provider/list', views.Provider().list, name="list_provider"),
    url(r'^provider/detail', views.Provider().detail, name="detail_provider"),
    url(r'^provider/edit', views.Provider().edit, name="edit_provider"),
    url(r'^idc/add', views.Idc().add, name="add_idc"),
    url(r'^idc/export', views.Idc().export, name="export_idc"),
    url(r'^idc/list', views.Idc().list, name="list_idc"),
    url(r'^idc/detail', views.Idc().detail, name="detail_idc"),
    url(r'^idc/edit', views.Idc().edit, name="edit_idc"),
    url(r'^rack/add', views.Rack().add, name="add_rack"),
    url(r'^rack/export', views.Rack().export, name="export_rack"),
    url(r'^rack/list', views.Rack().list, name="list_rack"),
    url(r'^rack/detail', views.Rack().detail, name="detail_rack"),
    url(r'^rack/edit', views.Rack().edit, name="edit_rack"),
    url(r'^bandwidth/add', views.Bandwidth().add, name="add_bandwidth"),
    url(r'^bandwidth/export', views.Bandwidth().export, name="export_bandwidth"),
    url(r'^bandwidth/list', views.Bandwidth().list, name="list_bandwidth"),
    url(r'^bandwidth/detail', views.Bandwidth().detail, name="detail_bandwidth"),
    url(r'^bandwidth/edit', views.Bandwidth().edit, name="edit_bandwidth"),
    url(r'^ip_segment/add', views.Ip_Segment().add, name="add_ip_segment"),
    url(r'^ip_segment/export', views.Ip_Segment().export, name="export_ip_segment"),
    url(r'^ip_segment/list', views.Ip_Segment().list, name="list_ip_segment"),
    url(r'^ip_segment/detail', views.Ip_Segment().detail, name="detail_ip_segment"),
    url(r'^ip_segment/edit', views.Ip_Segment().edit, name="edit_ip_segment"),
    url(r'^domain/add', views.Domain().add, name="add_domain"),
    url(r'^domain/export', views.Domain().export, name="export_domain"),
    url(r'^domain/list', views.Domain().list, name="list_domain"),
    url(r'^domain/detail', views.Domain().detail, name="detail_domain"),
    url(r'^domain/edit', views.Domain().edit, name="edit_domain"),
    url(r'^wechat_pubno/add', views.Wechat_Pubno().add, name="add_wechat_pubno"),
    url(r'^wechat_pubno/export', views.Wechat_Pubno().export, name="export_wechat_pubno"),
    url(r'^wechat_pubno/list', views.Wechat_Pubno().list, name="list_wechat_pubno"),
    url(r'^wechat_pubno/detail', views.Wechat_Pubno().detail, name="detail_wechat_pubno"),
    url(r'^wechat_pubno/edit', views.Wechat_Pubno().edit, name="edit_wechat_pubno"),
    url(r'^third_service/add', views.Third_Service().add, name="add_third_service"),
    url(r'^third_service/export', views.Third_Service().export, name="export_third_service"),
    url(r'^third_service/list', views.Third_Service().list, name="list_third_service"),
    url(r'^third_service/detail', views.Third_Service().detail, name="detail_third_service"),
    url(r'^third_service/edit', views.Third_Service().edit, name="edit_third_service"),
    url(r'^hardware_brand/add', views.Hardware_Brand().add, name="add_hardware_brand"),
    url(r'^hardware_brand/export', views.Hardware_Brand().export, name="export_hardware_brand"),
    url(r'^hardware_brand/list', views.Hardware_Brand().list, name="list_hardware_brand"),
    url(r'^hardware_brand/detail', views.Hardware_Brand().detail, name="detail_hardware_brand"),
    url(r'^hardware_brand/edit', views.Hardware_Brand().edit, name="edit_hardware_brand"),
    url(r'^hardware/add', views.Hardware().add, name="add_hardware"),
    url(r'^hardware/export', views.Hardware().export, name="export_hardware"),
    url(r'^hardware/list', views.Hardware().list, name="list_hardware"),
    url(r'^hardware/detail', views.Hardware().detail, name="detail_hardware"),
    url(r'^hardware/edit', views.Hardware().edit, name="edit_hardware"),
    url(r'^software_type/add', views.Software_Type().add, name="add_software_type"),
    url(r'^software_type/export', views.Software_Type().export, name="export_software_type"),
    url(r'^software_type/list', views.Software_Type().list, name="list_software_type"),
    url(r'^software_type/detail', views.Software_Type().detail, name="detail_software_type"),
    url(r'^software_type/edit', views.Software_Type().edit, name="edit_software_type"),
    url(r'^software/add', views.Software().add, name="add_software"),
    url(r'^software/export', views.Software().export, name="export_software"),
    url(r'^software/list', views.Software().list, name="list_software"),
    url(r'^software/detail', views.Software().detail, name="detail_software"),
    url(r'^software/edit', views.Software().edit, name="edit_software"),
    url(r'^person/add', views.Person().add, name="add_person"),
    url(r'^person/export', views.Person().export, name="export_person"),
    url(r'^person/list', views.Person().list, name="list_person"),
    url(r'^person/detail', views.Person().detail, name="detail_person"),
    url(r'^person/edit', views.Person().edit, name="edit_person"),
    url(r'^business_system/add', views.Business_System().add, name="add_business_system"),
    url(r'^business_system/export', views.Business_System().export, name="export_business_system"),
    url(r'^business_system/list', views.Business_System().list, name="list_business_system"),
    url(r'^business_system/detail', views.Business_System().detail, name="detail_business_system"),
    url(r'^business_system/edit', views.Business_System().edit, name="edit_business_system"),
    url(r'^position/add', views.Position().add, name="add_position"),
    url(r'^position/export', views.Position().export, name="export_position"),
    url(r'^position/list', views.Position().list, name="list_position"),
    url(r'^position/detail', views.Position().detail, name="detail_position"),
    url(r'^position/edit', views.Position().edit, name="edit_position"),
    url(r'^department/add', views.Department().add, name="add_department"),
    url(r'^department/export', views.Department().export, name="export_department"),
    url(r'^department/list', views.Department().list, name="list_department"),
    url(r'^department/detail', views.Department().detail, name="detail_department"),
    url(r'^department/edit', views.Department().edit, name="edit_department"),
]
